### PR TITLE
Fix array of authors render

### PR DESCRIPTION
**Pull request by ashalfarhan**
Need to handle if the author/creator is an array
Ref: https://github.com/janosh/awesome-svelte-kit/issues/34#issue-1038475160

### Screenshots

Before:
Screenshot 2021-11-01 002107

After:
image

I'm new to svelte, so please be advised 😊

### CODE REVIEW

**Comment by janosh** [comment]
Thanks, that was quick! Thinking about this more, we need to come at this from a slightly different angle. Sorry about this.

Having the creators, their websites and twitter handles be separate arrays can turn into a mess. To ensure they're all the same length, we'd need to fill up with `null` or empty strings if some authors are missing URLs or Twitter. So let's convert the `creator` field itself to an array of objects named `creators`, each of which may or may not have a `url`, `twitter`, 'github`, `email`, etc. field.

I just pushed a commit applying this change to `sites.yml`. Could you try to update `SiteDetails.svelte` again to match?

**Comment by ashalfarhan** [comment]
Sure

**Comment by janosh** [comment]
Much better already. Probably should have mentioned that with this change, it makes sense to render all data per creator in a single place. I.e. don't iterate over the creators array twice but move the Twitter links into the same list as the names and URLs.

**Comment by ashalfarhan** [comment]
If you don't mind, wdyt about this?
image

**Comment by janosh** [comment]
Yep, that looks great. Could you increase the white space between names and icons slightly?

**Comment by ashalfarhan** [comment]
> Yep, that looks great. Could you increase the white space between names and icons slightly?

Okay, please check them up

**Comment by janosh** [comment]
Thanks for this contribution! 👍

**Pull request merged**
