### PR TITLE
Add sveltekit-starter-blog by Scott Spence

### PR DESCRIPTION
**Pull request by endymion1818**
Add starter that was made by Scott Spence, it's a really good starter that I enjoy using. Hope that's OK.

### CODE REVIEW

**Comment by janosh** [comment]
This is great! 👍  Could you please also add the starter to `sites.yml`?

**Comment by endymion1818** [comment]
Done!

**Comment by janosh** [comment]
I noticed there's a typo in your post url: `https://scottspence.com/2021/05/06/graphcms-svelte-strter`. Missing an 'a' in starter. Do you want to fix that before I merge?

**Comment by endymion1818** [comment]
Wow good spot! I've asked Scott about it, Ill let you know

**Comment by spences10** [comment]
Yeah, the typo isn't intentional but I didn't spot it until I'd polished it already 😂

It's not had a great deal of traffic so can change it if that's preferred

**Comment by endymion1818** [comment]
He is going to leave the URL like that apparently, I'm happy to merge it it you are.

**Comment by janosh** [comment]
Thanks @endymion1818 for this contribution and @spences10 for fixing the URL!

**Pull request merged**
