### PR TITLE
Comprehensive sveltekit experiments sample app

### PR DESCRIPTION
**Pull request by tsukhu**
An ongoing app for sveltekit using Tailwind, Firebase v9, vercel that brings out the awesome features of svelte kit

### CODE REVIEW

**Comment by janosh** [comment]
Thanks! Would you mind adding your site to the readme as well?

**Comment by tsukhu** [comment]
@janosh Thank you for considering this project.
I have added the site in the readme as a link now.
Also actively working on it. The next is to add a graphql endpoint . https://sveltekit-demo-psi.vercel.app/api/london.weather.json where the [city].weather.json works . I will be adding UI for it
Let me know if anything else is missing.

**Comment by tsukhu** [comment]
Ahh I guess you meant your readme :-)

**Comment by tsukhu** [comment]
will do it

**Comment by tsukhu** [comment]
Added to Readme as well

**Comment by janosh** [comment]
> Ahh I guess you meant your readme :-)

Yes, exactly. 😄 

Perhaps I should make this sentence in the readme more prominent?

> Remember to add each new site both to the readme and to `sites.yml`.

**Comment by janosh** [comment]
Thanks for this contribution! 👍

**Pull request merged**
