### PR TITLE
add inlang

### PR DESCRIPTION
**Pull request by samuelstroschein**
The inlang dashboard uses SvelteKit.

### CODE REVIEW

**Comment by samuelstroschein** [comment]
Whoops, I think I crashed the CI pipeline by making a subsequent commit while the CI pipeline was modifying some files.

**Comment by janosh** [comment]
Thanks! How do you actually view the dashboard? Does it require signing in? Linking to the landing page doesn't make much sense if that's written in Next? Are you planning to move the landing page to SvelteKit?

**Comment by samuelstroschein** [comment]
I was about to ask that. 

Should I link to the dashboard instead of the landing page since the dashboard requires a login? 

The dashboards URL is [https://app.inlang.dev](https://app.inlang.dev). 
The git path https://github.com/inlang/inlang/tree/main/apps/dashboard

**Comment by janosh** [comment]
Then let's add a `siteSrc` field of `https://github.com/inlang/inlang/tree/main/apps/dashboard`. Using the dashboard's URL https://app.inlang.dev would be more accurate but the site screenshot wouldn't look nearly as catchy of course. 😄

**Pull request merged**
