### PR TITLE
update urara screenshot

### PR DESCRIPTION
**Pull request by kwaa**
🤔 It looks better now

### CODE REVIEW

**Comment by janosh** [comment]
Thanks, I agree the new screenshot looks better. The problem is, all the screenshots are auto-generated by [`site/scripts/takeScreenshots.js`](https://github.com/janosh/awesome-svelte-kit/blob/7b9f8a7cfb999f50cc817a1ce4df3eb895874fa7/site/scripts/takeScreenshots.js) and auto-updated every 3 months by the GitHub action in [`.github/workflows/updateScreenshots.yml`](https://github.com/janosh/awesome-svelte-kit/blob/7b9f8a7cfb999f50cc817a1ce4df3eb895874fa7/.github/workflows/updateScreenshots.yml). So if we merge this now, it would be reverted in a month or so.

What did you do to get the better screenshot? Zoom in on the page? Make the window smaller? Perhaps we could store metadata with each site that specifies the values for `clip` in Puppeteer's [`page.screenshot()`](https://pptr.dev/#?product=Puppeteer&version=v10.4.0&show=api-pagescreenshotoptions) options.

**Comment by kwaa** [comment]
> Thanks, I agree the new screenshot looks better. The problem is, all the screenshots are auto-generated by [`site/scripts/takeScreenshots.js`](https://github.com/janosh/awesome-svelte-kit/blob/7b9f8a7cfb999f50cc817a1ce4df3eb895874fa7/site/scripts/takeScreenshots.js) and auto-updated every 3 months by the GitHub action in [`.github/workflows/updateScreenshots.yml`](https://github.com/janosh/awesome-svelte-kit/blob/7b9f8a7cfb999f50cc817a1ce4df3eb895874fa7/.github/workflows/updateScreenshots.yml). So if we merge this now, it would be reverted in a month or so.
> 
> What did you do to get the better screenshot? Zoom in on the page? Make the window smaller? Perhaps we could store metadata with each site that specifies the values for `clip` in Puppeteer's [`page.screenshot()`](https://pptr.dev/#?product=Puppeteer&version=v10.4.0&show=api-pagescreenshotoptions) options.

The demo site defaults to light or dark theme, but I manually set it to valentine theme. That is: `<html data-theme="valentine">`

**Comment by kwaa** [comment]
> > Thanks, I agree the new screenshot looks better. The problem is, all the screenshots are auto-generated by [`site/scripts/takeScreenshots.js`](https://github.com/janosh/awesome-svelte-kit/blob/7b9f8a7cfb999f50cc817a1ce4df3eb895874fa7/site/scripts/takeScreenshots.js) and auto-updated every 3 months by the GitHub action in [`.github/workflows/updateScreenshots.yml`](https://github.com/janosh/awesome-svelte-kit/blob/7b9f8a7cfb999f50cc817a1ce4df3eb895874fa7/.github/workflows/updateScreenshots.yml). So if we merge this now, it would be reverted in a month or so.
> > What did you do to get the better screenshot? Zoom in on the page? Make the window smaller? Perhaps we could store metadata with each site that specifies the values for `clip` in Puppeteer's [`page.screenshot()`](https://pptr.dev/#?product=Puppeteer&version=v10.4.0&show=api-pagescreenshotoptions) options.
> 
> The demo site defaults to light or dark theme, but I manually set it to valentine theme. That is: `<html data-theme="valentine">`

🤔 So if want auto-generated screenshots to use the valentine theme by default, need `localStorage.setItem('theme','valentine')` ...

**Comment by janosh** [comment]
I guess it would be a lot of work for not much gain to apply specific options for a site when taking the screenshot. Perhaps you could just change urara's default theme to `valentine`?

**Comment by kwaa** [comment]
> I guess it would be a lot of work for not much gain to apply specific options for a site when taking the screenshot. Perhaps you could just change urara's default theme to `valentine`?

u're right. mainly the valentine theme is more eye-catching (in preview), but as a template, it needs a more neutral theme;
so be it. (btw, for the design of awesome-svelte-kit.netlify.app, I think DaisyUI can be used as a reference)

**Pull request closed without merging**
